name: WakaTime Readme

on:
  schedule:
    - cron: "0 */6 * * *"  # обновление каждые 6 часов
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LOC_CHART: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_COMMIT: "True"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          LANGUAGES: "1C, ABAP, ActionScript, Ada, Agda, AL, Android, Angular, Ant Build System, Apex, AppleScript, Assembly, ATS, AutoHotkey, Awk, BASH, Batchfile, C, C#, C++, Clojure, CoffeeScript, Crystal, CSS, Dart, Django, Dockerfile, Elm, Erlang, F#, Fortran, Go, Groovy, Haskell, HTML, Java, JavaScript, Julia, Kotlin, LaTeX, Less, Lua, Makefile, Markdown, Objective-C, Pascal, Perl, PHP, Prolog, Python, R, Ruby, Rust, Scala, Scheme, Shell, SQL, Swift, TypeScript, VBScript, Visual Basic, XML, YAML, Other"
